@EAppointment.WebAPI_HostAddress = http://localhost:5014

POST {{EAppointment.WebAPI_HostAddress}}/api/auths
Accept: application/json
Content-Type: application/json

{
  "UsernameOrEmail":"admin",
  "Password":"1"
}
###
GET {{EAppointment.WebAPI_HostAddress}}/api/doctors
Accept: application/json
{

}