@EAppointment.WebAPI_HostAddress = http://localhost:5014

POST {{EAppointment.WebAPI_HostAddress}}/api/auths/login
Accept: application/json
Content-Type: application/json

{
  "UsernameOrEmail":"admin",
  "Password":"1"
}
###
